import { Roboto_Slab } from "next/font/google";

const robotoSlab = Roboto_Slab({ subsets: ["latin"] });

export const metadata = {
  title: "First App",
  description: "Generated by create next app",
};


const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body className={robotoSlab.className}>{children}</body>
    </html>
  );
}

export default RootLayout;