import "bootstrap/dist/css/bootstrap.min.css";

import { Roboto_Slab } from "next/font/google";

const robotoSlab = Roboto_Slab({ subsets: ["latin"] });

export const metadata = {
  title: {
    default: "MaxiBreak",
    template: "%s | MaxiBreak",
  },
  description: "Generated by create next app",
};


const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body className={robotoSlab.className}>{children}</body>
    </html>
  );
}

export default RootLayout;